### ISSUE TITLE
Data to add

### ISSUE THREAD

**Issue by samlawhon** [samlawhon/eldora#3]
* Routes - strava login to suggest nearby routes
* Weather info to assess: likelihood of rain, how much warm clothing to bring - where from? https://openweathermap.org/api/statistics-api; forecasts: https://openweathermap.org/api
* Water to bring (takes as inputs: altitude, suspected pace)
* Cell data
* Water sources
* What kind of sunscreen to bring

**Comment by slawhon213** [comment]
* When to leave

**Comment by slawhon213** [comment]
* Snowed recently
